#!/usr/bin/env python3
import os
if "BOBOB" in os.environ:
    print(os.environ["BOBOB"])
os.environ["BOBOB"] = "hello hello"
print(os.environ["BOBOB"])

text = """
${HOME}
${BOBOB}
"""

print(os.path.expandvars(text))

# import jm_tools
# import jm_tools.docker as jmd

# r = jmd.get_available_services(["docker-compose.yml"])
# print(r)